os: linux
dist: xenial
language: python
sudo: false
python:
  - "3.6"
  - "3.7"

install:
  - pip install codecov
  - pip install .

script:
  - cd test
  - coverage run entry.py

after_success:
  - codecov --token=$CODECOV_TOKEN
